workflows:
  unity-ios:
    name: Unity iOS Build
    max_build_duration: 60
    environment:
      vars:
        UNITY_VERSION: "2022.3.61f1"
        UNITY_HASH: "46b0af2a28c3"
      xcode: latest

    scripts:
      - name: Install Unity Editor
        script: |
          echo "Downloading Unity Editor..."
          curl -L -o Unity.pkg "https://download.unity3d.com/download_unity/$UNITY_HASH/MacEditorInstaller/Unity.pkg"
          ls -lh Unity.pkg
          sudo installer -pkg Unity.pkg -target /

      - name: Install Unity iOS Build Support
        script: |
          echo "Downloading Unity iOS Build Support..."
          curl -L -o Unity-iOS.pkg "https://download.unity3d.com/download_unity/$UNITY_HASH/MacEditorTargetInstaller/UnitySetup-iOS-Support-for-Editor-$UNITY_VERSION.pkg"
          ls -lh Unity-iOS.pkg
          sudo installer -pkg Unity-iOS.pkg -target /

      - name: Build Unity iOS Project
        script: |
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -quit -batchmode \
            -projectPath . \
            -executeMethod BuildScript.BuildiOS \
            -buildTarget iOS

    artifacts:
      - build/ios/**/*
