workflows:
  unity-ios:
    name: Unity iOS Build (No License Required)
    max_build_duration: 60
    environment:
      vars:
        UNITY_VERSION: "2022.3.20f1"
      xcode: latest

    scripts:
      - name: Install Unity with iOS modules
        script: |
          curl -s https://raw.githubusercontent.com/game-ci/unity-ci-tools/main/install-unity.sh | bash -s -- "$UNITY_VERSION" ios

      - name: Build Unity iOS
        script: |
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -projectPath . \
            -buildTarget iOS \
            -quit -batchmode \
            -executeMethod BuildScript.BuildiOS

      - name: Build IPA (Xcode)
        script: |
          cd build/ios
          xcodebuild -project Unity-iPhone.xcodeproj \
            -scheme Unity-iPhone \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath output.xcarchive

          x
