workflows:
  unity_ios:
    name: Build Unity iOS
    environment:
      vars:
        UNITY_VERSION: "2022.3.61f1"
      xcode: latest
      cocoapods: default
      groups:
        - unity

    scripts:
      - name: Install Unity with iOS support
        script: |
          unityhub install $UNITY_VERSION --modules ios

      - name: Activate Unity (free license, no activation needed)
        script: |
          echo "Using Unity free license"

      - name: Build Unity to Xcode (iOS)
        script: |
          /Applications/Unity/Hub/Editor/$UNITY_VERSION/Unity.app/Contents/MacOS/Unity \
            -batchmode \
            -quit \
            -logFile /dev/stdout \
            -projectPath . \
            -executeMethod BuildScript.BuildiOS

      - name: Build IPA using Xcode
        script: |
          xcode-project build-ipa \
            --project "build/ios/Unity-iPhone.xcodeproj" \
            --scheme "Unity-iPhone"

    artifacts:
      - build/ios/**/*.ipa
